version: '3.5'
services:
  scraper:
    build: .
    container_name: scraper-marcos
    environment:
      - CONFIG_FILE=/scraper/config.json
    volumes:
      - $PWD/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  metanet1:
    driver: bridge