version: '3.5'
services:
  scraper:
    build: .
    container_name: scraper-marcos
    environment:
      - CONFIG_FILE=/scraper/config.json
      - DATABASE_URL=mysql+mysqldb://linroot:uKQORbgnUy7-EYrY@lin-28781-15425-mysql-primary.servers.linodedb.net/exchanges_db?ssl_mode=DISABLE
    volumes:
      - $PWD/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  metabase-app:
    image: metabase/metabase:latest
#    image: metabase/metabase:v0.43.1
    container_name: metabase-marcos
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - $PWD:/metabase-data
      - $PWD/data:/data
    ports:
      - 3001:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - metanet1
    depends_on:
      - scraper
networks:
  metanet1:
    driver: bridge